# Generated by Django 2.2.5 on 2019-11-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('edition', models.IntegerField(default=1)),
                ('author', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('age_group', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('coordinate', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('opening_hour', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Book')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Store')),
            ],
        ),
    ]
